# the image is base on the python:3.7 image
FROM python:3.7

# create a workfolder in the image to make sure all the works done in the folder
WORKDIR /app

# install pandas for the python script
RUN pip install pandas==1.3.5 

# add python script into the image
ADD py_script.py /app

# create environment variables for python script
ENV INPUT_DIR='/app/input'
ENV OUTPUT_DIR='/app/output'

# make sure the container keep on running
CMD tail -f /dev/null  

# Use below command to build the image
# cd /Users/huijin/Desktop/DataEngineeringLearning/Lab2-Docker/CsvCombine
# docker build -f dockerfile -t lab2_csv_combine:latest .

# Use below command to launch container
# docker container run --rm -t -d -v /Users/huijin/Desktop/DataEngineeringLearning/Lab2-Docker/CsvCombine/input:/app/input -v /Users/huijin/Desktop/DataEngineeringLearning/Lab2-Docker/CsvCombine/output:/app/output lab2_csv_combine

# Use below command to run the python script on container
# docker container run <containerID> python3 /app/py_script.py

# Use below command to clean up, the container should clean up automatically since -rm is specified when launching the container
# docker container stop <containerID>

